/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package commander.View;

import commander.DAO.UserDAO;


/**
 *
 * @author dm200
 */
public class Index extends javax.swing.JFrame {

    /**
     * Creates new form Index
     */
    public Index() {
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnUsersView = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnProductsView = new javax.swing.JButton();
        btnDishesView = new javax.swing.JButton();
        btnOrderView = new javax.swing.JButton();
        btnCommanderView = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));
        setSize(new java.awt.Dimension(600, 400));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setMaximumSize(new java.awt.Dimension(600, 400));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        jLabel1.setText("Bienvenido");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        btnUsersView.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnUsersView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/commander/images/usuarios.png"))); // NOI18N
        btnUsersView.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsersView.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnUsersView.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUsersView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsersViewActionPerformed(evt);
            }
        });
        jPanel1.add(btnUsersView, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 120, 80));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel2.setText("Administrar:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        btnProductsView.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnProductsView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/commander/images/productos.png"))); // NOI18N
        btnProductsView.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProductsView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductsViewActionPerformed(evt);
            }
        });
        jPanel1.add(btnProductsView, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 120, 80));

        btnDishesView.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDishesView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/commander/images/comanda.png"))); // NOI18N
        btnDishesView.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDishesView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDishesViewActionPerformed(evt);
            }
        });
        jPanel1.add(btnDishesView, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 120, 80));

        btnOrderView.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnOrderView.setText("Ordenes");
        btnOrderView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderViewActionPerformed(evt);
            }
        });
        jPanel1.add(btnOrderView, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, -1));

        btnCommanderView.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCommanderView.setText("Comanda");
        btnCommanderView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommanderViewActionPerformed(evt);
            }
        });
        jPanel1.add(btnCommanderView, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel3.setText("Órdenes");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel4.setText("Usuarios");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel5.setText("Productos");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsersViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsersViewActionPerformed
        UserView myUsersView = new UserView();
        myUsersView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUsersViewActionPerformed

    private void btnProductsViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductsViewActionPerformed
        ProductView myProductView = new ProductView();
        myProductView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnProductsViewActionPerformed

    private void btnDishesViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDishesViewActionPerformed
        DishView myDishesView = new DishView();
        myDishesView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDishesViewActionPerformed

    private void btnOrderViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderViewActionPerformed
        OrderView myOrderView = new OrderView();
        myOrderView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnOrderViewActionPerformed

    private void btnCommanderViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommanderViewActionPerformed
        CommanderView myCommanderView = new CommanderView();
        myCommanderView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCommanderViewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCommanderView;
    private javax.swing.JButton btnDishesView;
    private javax.swing.JButton btnOrderView;
    private javax.swing.JButton btnProductsView;
    private javax.swing.JButton btnUsersView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
